Repository SalesforceFoundation/PMM, pull requests merged in 2020-12, with the labels that each got.

#363 Print Attendance Roster
  force-app/main/default/flexipages/Attendance.flexipage-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/lwc/attendance/__tests__/attendance.test.js
  force-app/main/default/lwc/attendance/__tests__/data/currentPageReference.json
  force-app/main/default/lwc/attendance/attendance.html
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendance/attendance.js-meta.xml
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
  force-app/main/default/staticresources/pmm/attendancePrintOverride.css
  force-app/main/default/tabs/Attendance.tab-meta.xml
Labels: in QE review

#364 Drive recent sessions display with field set
  force-app/main/default/classes/FieldSetController.cls
  force-app/main/default/classes/FieldSetController_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/lwc/formattedField/__tests__/formattedField.test.js
  force-app/main/default/lwc/formattedField/formattedField.html
  force-app/main/default/lwc/formattedField/formattedField.js
  force-app/main/default/lwc/formattedField/formattedField.js-meta.xml
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/sessionCard/sessionCard.html
  force-app/main/default/lwc/sessionCard/sessionCard.js
  force-app/main/default/objects/ServiceSession__c/fieldSets/RecentSessionsView.fieldSet-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
  package.json
Labels: in QE review

#370 [Robot] Create service session checkbox on wizard
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen4.robot
Labels: 🤖 test

#371 Handle updates on fields in fieldset
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
Labels: in QE review

#372 Fix unstable tests using service schedule model wrapper
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
Labels: ready to merge

#373 Check CRUD and FLS before displaying Add More Participants quick action modal
  force-app/main/default/classes/PermissionValidator.cls
  force-app/main/default/classes/PermissionValidator_TEST.cls
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/participantAdder/participantAdder.html
  force-app/main/default/lwc/participantAdder/participantAdder.js
Labels: in QE review

#374 Skip selected participants in Attendance
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
Labels: in QE review

#378 Upgrade to 3.23.0, remove unneeded options
  cumulusci.yml
  tasks/GenericSrcRevert.py
Labels: in QE review

#368 Monthly Recurrence options
  force-app/main/default/classes/MonthlyIterable.cls
  force-app/main/default/classes/MonthlyIterable_TEST.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls
  force-app/main/default/classes/RecurrenceService.cls
  force-app/main/default/classes/RecurrenceService_TEST.cls
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/objects/ServiceSchedule__c/fields/MonthlyRecurrenceOption__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review

#376 Add list view filter to recent sessions home page component.
  force-app/main/default/classes/PermissionValidator_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/formattedField/__tests__/formattedField.test.js
  force-app/main/default/lwc/listViewSelector/__tests__/data/getListViews.json
  force-app/main/default/lwc/listViewSelector/__tests__/listViewSelector.test.js
  force-app/main/default/lwc/listViewSelector/listViewSelector.html
  force-app/main/default/lwc/listViewSelector/listViewSelector.js
  force-app/main/default/lwc/listViewSelector/listViewSelector.js-meta.xml
  force-app/main/default/lwc/recentSessions/recentSessions.css
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/scopedNotification/scopedNotification.js
  force-app/main/default/objects/ServiceSession__c/listViews/All.listView-meta.xml
  force-app/main/default/staticresources/pmm/listViewSelectorOverrides.css
  force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
Labels: in QE review

#385 Add cause to error message; easily create Rosa user
  cumulusci.yml
  force-app/main/default/classes/Util.cls
  unpackaged/users/rosa.json
Labels: in QE review

#384 [Robot] Added test for max service sessions on wizard
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/locators_50.py
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen2.robot
Labels: 🤖 test

#386 Remove report charts from flexi pages
  force-app/main/default/flexipages/Program_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Service_Record_Page.flexipage-meta.xml
Labels: in QE review
