Repository SalesforceFoundation/PMM, pull requests merged in 2020-06, with the labels that each got.

#219 Files related list on program enagagement
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
Labels: in QE review

#218 Mass quick action to update cohorts
  force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
  force-app/main/default/quickActions/ProgramEngagement__c.Add_to_Program_Cohort.quickAction-meta.xml
Labels: in QE review

#216 Disable done and add entry button on BSDT
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: in QE review

#221 Fix program cohort on program engagement records
  data/bulk/data.sql
Labels: in QE review

#222 Modal component jest tests
  .gitignore
  force-app/main/default/lwc/modal/__tests__/modal.test.js
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/currentPageReference.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getFieldSet.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/newProgramEngagement.test.js
  jest.config.js
  jest.setup.js
  package-lock.json
  package.json
  sfdx-project.json
  yarn.lock
Labels: no QE needed, ready to merge

#225 added date validation for program
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Program/create_program.robot
Labels: 🤖 test

#228 Add service new service delivery quick action
  force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
  force-app/main/default/quickActions/Service__c.CreateServiceDelivery.quickAction-meta.xml
Labels: in QE review

#233 add date validation for PE
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
Labels: 🤖 test

#232 added date validation for cohort
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/ProgramCohortPageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
Labels: 🤖 test

#231 Update error email address with distribution email
  force-app/main/default/classes/InstallScript.cls
Labels: no QE needed, wait to merge

#230 BSDT changes
  cumulusci.yml
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ServiceDeliveryController.cls
  force-app/main/default/classes/ServiceDeliveryController_TEST.cls
  force-app/main/default/classes/ServiceSelector.cls
  force-app/main/default/classes/ServiceSelector_TEST.cls
  force-app/main/default/classes/ServiceService.cls
  force-app/main/default/classes/ServiceService_TEST.cls
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
  force-app/main/default/objects/ProgramEngagement__c/fields/Contact__c.field-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Bulk_Service_Deliveries.fieldSet-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/fields/ProgramEngagement__c.field-meta.xml
Labels: in QE review

#235 BSDT bug fix
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: in QE review

#234 Add PE waitlisted stage
  force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
Labels: in QE review
