Repository SalesforceFoundation/PMM, pull requests merged in 2020-08, with the labels that each got.

#261 Update StartDate population on Program Engagement
  unpackaged/config/dev/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
Labels: in QE review

#264 [Robot] Fix BSDT Tests
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/create_prog_engagement.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
Labels: 🤖 test

#262 Open source service delivery reports
  cumulusci.yml
  metadeploy/labels_en.json
  unpackaged/post/reports/package.xml
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/My_Service_Deliveries_Last_Month_J5z.report
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/My_Service_Delivery_by_Client_Last_Month_nw5.report
Labels: in QE review

#266 Summer 2020 Translations
  force-app/main/default/objectTranslations/Contact-ja/Contact-ja.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-de/ProgramEngagement__c-de.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-de/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-de/StartDate__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-en_GB/Account__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-en_GB/ProgramEngagement__c-en_GB.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-en_GB/Role__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-en_GB/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-es/ProgramEngagement__c-es.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-es/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-es_MX/ProgramEngagement__c-es_MX.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-es_MX/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr/AutoName_Override__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr/ProgramEngagement__c-fr.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr_CA/AutoName_Override__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr_CA/ProgramEngagement__c-fr_CA.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-fr_CA/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-ja/Account__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-ja/ProgramEngagement__c-ja.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-ja/Role__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-ja/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-nl_NL/ProgramEngagement__c-nl_NL.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ProgramEngagement__c-nl_NL/Stage__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Program__c-nl_NL/Program__c-nl_NL.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-de/ServiceDelivery__c-de.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-en_GB/Account__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-en_GB/ServiceDelivery__c-en_GB.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-en_GB/Service_Provider__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-es/ServiceDelivery__c-es.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-es_MX/ServiceDelivery__c-es_MX.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-fr/ServiceDelivery__c-fr.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-fr_CA/ServiceDelivery__c-fr_CA.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-ja/Account__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-ja/ServiceDelivery__c-ja.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-ja/Service_Provider__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-nl_NL/ServiceDelivery__c-nl_NL.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-fr/UnitOfMeasurement__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-fr_CA/UnitOfMeasurement__c.fieldTranslation-meta.xml
  force-app/main/default/translations/de.translation-meta.xml
  force-app/main/default/translations/en_GB.translation-meta.xml
  force-app/main/default/translations/es.translation-meta.xml
  force-app/main/default/translations/es_MX.translation-meta.xml
  force-app/main/default/translations/fr.translation-meta.xml
  force-app/main/default/translations/fr_CA.translation-meta.xml
  force-app/main/default/translations/ja.translation-meta.xml
  force-app/main/default/translations/nl_NL.translation-meta.xml
Labels: in dev review, ready for QE

#265 Refactor Automation for CCI 3.16
  cumulusci.yml
  data/bulk/data.sql
  data/bulk/mapping/Contacts.yml
  data/bulk/mapping/Household_Accounts.yml
  data/bulk/mapping/Organization_Accounts.yml
  data/bulk/mapping/npsp/GW_Volunteers.yml
  data/bulk/mapping/npsp/npe01.yml
  data/bulk/mapping/npsp/npe03.yml
  data/bulk/mapping/npsp/npe4.yml
  data/bulk/mapping/npsp/npe5.yml
  data/bulk/mapping/npsp/npo02.yml
  data/bulk/mapping/npsp/npsp.yml
  data/bulk/mapping/pmdm/pmdm.yml
  datasets/mapping.yml
  datasets/sample.sql
  tasks/BulkData.py
  tasks/UpdateClientPhotoDirectories.py
  tasks/UploadClientPhotos.py
  tasks/logger.py
  tasks/namespaces.py
Labels: in QE review

#269 Enable GitHub Actions for PMM
  .eslintignore
  .eslintrc.yml
  .flake8
  .github/CODEOWNERS
  .github/workflows/eslint.yml
  .github/workflows/jest.yml
  .github/workflows/label_audit.yml
  .github/workflows/lockfile-lint.yml
  .github/workflows/prettier.yml
  .github/workflows/python.yml
  .gitignore
  .huskyrc.json
  .lintstagedrc
  .lockfile-lintrc.yml
  .prettierrc.yml
  CODE_OF_CONDUCT.md
  data/scripts/update_all_records_as_recently_viewed.apex
  force-app/main/default/lwc/newProgramEngagement/__tests__/newProgramEngagement.test.js
  metadeploy/labels_en.json
  orgs/trial.json
  package.json
  pyproject.toml
  requirements.txt
  robot/pmm/resources/BaseObjects.py
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ContactPageObject.py
  robot/pmm/resources/ProgramCohortPageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ProgramPageObject.py
  robot/pmm/resources/ServiceDeliveryPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  scripts/install-pre-commit.sh
  scripts/label_audit.py
  scripts/pre-commit.sh
  scripts/update-dependencies.sh
  scripts/update-python-dependencies.sh
  tasks/GenericSrcRevert.py
  unpackaged/tests/serviceDeliveryModal/lwc/testModal/testModal.js
  yarn.lock
Labels: ready for review

#268 Add Feature Parameters to Count Permission Set Assignments
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/featureParameters/PermSetDeliverUsers.featureParameterInteger-meta.xml
  force-app/main/default/featureParameters/PermSetManageUsers.featureParameterInteger-meta.xml
Labels: ready for review

#276 Review sessions component
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.js-meta.xml
  force-app/main/default/lwc/util/util.js
Labels: in QE review
