Repository SalesforceFoundation/PMM, pull requests merged in 2020-09, with the labels that each got.

#272 Service Schedule Wizard
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp-meta.xml
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleHelper.js
  force-app/main/default/flows/ScheduleCreator.flow-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/flowNavigationApi/flowNavigationApi.html
  force-app/main/default/lwc/flowNavigationApi/flowNavigationApi.js
  force-app/main/default/lwc/flowNavigationApi/flowNavigationApi.js-meta.xml
  force-app/main/default/lwc/footer/footer.html
  force-app/main/default/lwc/footer/footer.js
  force-app/main/default/lwc/footer/footer.js-meta.xml
  force-app/main/default/lwc/modal/__tests__/modal.test.js
  force-app/main/default/lwc/modal/modal.css
  force-app/main/default/lwc/modal/modal.html
  force-app/main/default/lwc/modal/modal.js
  force-app/main/default/lwc/section/section.html
  force-app/main/default/lwc/section/section.js
  force-app/main/default/lwc/section/section.js-meta.xml
  force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
  force-app/main/default/lwc/serviceScheduleCreator/navigationItems.js
  force-app/main/default/lwc/serviceScheduleCreator/progressStep.js
  force-app/main/default/lwc/serviceScheduleCreator/progressSteps.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js-meta.xml
  force-app/main/default/messageChannels/Navigation.messageChannel-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
Labels: in QE review

#280 Feature/winter 21 labels
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleHelper.js
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
  force-app/main/default/layouts/ServiceParticipant__c-Service Participant Layout.layout-meta.xml
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.js-meta.xml
  force-app/main/default/lwc/serviceScheduleCreator/navigationItems.js
  force-app/main/default/lwc/serviceScheduleCreator/progressStep.js
  force-app/main/default/lwc/serviceScheduleCreator/progressSteps.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/objectTranslations/ServiceParticipant__c-en_US/SignedUpOn__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-en_US/TotalCapacity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-en_US/SessionDate__c.fieldTranslation-meta.xml
  force-app/main/default/objects/ServiceParticipant__c/fields/SignUpDate__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fieldSets/ServiceScheduleInformation.fieldSet-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/AllDay__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/CreateServiceSessionRecords__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/DaysOfWeek__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionEnd__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionStart__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/Frequency__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/NumberOfServiceSessions__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantCapacity__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/ServiceScheduleEndDate__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/ServiceScheduleEnds__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/SessionEnd__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/SessionStart__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: ready for review

#275 Clear vulns via NPM updates
  .flake8
  .github/workflows/lockfile-lint.yml
  .lintstagedrc
  .prettierignore
  cumulusci.yml
  force-app/main/default/flexipages/Bulk_Service_Deliveries.flexipage-meta.xml
  force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Program_Cohort_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Program_Engagement_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Program_Management_Home.flexipage-meta.xml
  force-app/main/default/flexipages/Program_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Service_Delivery_Record_Page.flexipage-meta.xml
  force-app/main/default/flexipages/Service_Record_Page.flexipage-meta.xml
  jest.config.js
  package.json
  pyproject.toml
  sfdx-project.json
  yarn.lock
Labels: in dev review

#278 Schedule wizard step 1
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js-meta.xml
  force-app/main/default/lwc/picklist/picklist.html
  force-app/main/default/lwc/picklist/picklist.js
  force-app/main/default/lwc/picklist/picklist.js-meta.xml
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/section/section.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
Labels: in QE review

#282 Fix Program Engagement Process Builder
  cumulusci.yml
  force-app/main/default/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
Labels: in QE review

#279 Service Schedule Wizard: Step 4 Review
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/lwc/outputField/outputField.html
  force-app/main/default/lwc/outputField/outputField.js
  force-app/main/default/lwc/outputField/outputField.js-meta.xml
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review

#284 RRules
  force-app/main/default/classes/DailyIterator.cls
  force-app/main/default/classes/DailyIterator.cls-meta.xml
  force-app/main/default/classes/DailyIterator_TEST.cls
  force-app/main/default/classes/DailyIterator_TEST.cls-meta.xml
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/RecurrenceFactory.cls
  force-app/main/default/classes/RecurrenceFactory.cls-meta.xml
  force-app/main/default/classes/RecurrenceFactoryInterface.cls
  force-app/main/default/classes/RecurrenceFactoryInterface.cls-meta.xml
  force-app/main/default/classes/RecurrenceFactory_TEST.cls
  force-app/main/default/classes/RecurrenceFactory_TEST.cls-meta.xml
  force-app/main/default/classes/RecurrenceIteratorInterface.cls
  force-app/main/default/classes/RecurrenceIteratorInterface.cls-meta.xml
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule.cls-meta.xml
  force-app/main/default/classes/RecurrenceRule_TEST.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls-meta.xml
  force-app/main/default/classes/RecurrenceService.cls
  force-app/main/default/classes/RecurrenceService.cls-meta.xml
  force-app/main/default/classes/RecurrenceService_TEST.cls
  force-app/main/default/classes/RecurrenceService_TEST.cls-meta.xml
Labels: ready for review

#289 Service Schedule to Service Session relationship changed to lookup
  force-app/main/default/objects/ServiceSession__c/ServiceSession__c.object-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/ServiceSchedule__c.field-meta.xml
Labels: ready for QE

#286 RRule builder and parser, DailyIterator
  force-app/main/default/classes/DailyIterator.cls
  force-app/main/default/classes/DailyIterator_TEST.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls
Labels: ready for review

#287 Feature/winter 21 add service participants
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/ProgramTestDataFactory.cls
  force-app/main/default/classes/SelectParticipantController.cls
  force-app/main/default/classes/SelectParticipantController.cls-meta.xml
  force-app/main/default/classes/SelectParticipantController_TEST.cls
  force-app/main/default/classes/SelectParticipantController_TEST.cls-meta.xml
  force-app/main/default/classes/SelectParticipantService.cls
  force-app/main/default/classes/SelectParticipantService.cls-meta.xml
  force-app/main/default/classes/SelectParticipantService_TEST.cls
  force-app/main/default/classes/SelectParticipantService_TEST.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/participantSelector/participantSelector.css
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/participantSelector/participantSelector.js-meta.xml
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
Labels: in QE review

#290 Adding Participant Related list to Contact Layout
  force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
Labels: in QE review

#292 Add missing Winter21 strings
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/Interval__c.field-meta.xml
Labels: ready for review

#291 Recurrence: Weekly Iterator
  force-app/main/default/classes/DailyIterator.cls
  force-app/main/default/classes/DailyIterator_TEST.cls
  force-app/main/default/classes/RecurrenceFactory.cls
  force-app/main/default/classes/RecurrenceFactory_TEST.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceService.cls
  force-app/main/default/classes/RecurrenceService_TEST.cls
  force-app/main/default/classes/WeeklyIterator.cls
  force-app/main/default/classes/WeeklyIterator.cls-meta.xml
  force-app/main/default/classes/WeeklyIterator_TEST.cls
  force-app/main/default/classes/WeeklyIterator_TEST.cls-meta.xml
Labels: ready for review

#285 Create data model and pass it to and from screen 1 and save on screen 4
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleHelper.js
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/classes/PermissionValidator.cls
  force-app/main/default/classes/PermissionValidator.cls-meta.xml
  force-app/main/default/classes/PermissionValidator_TEST.cls
  force-app/main/default/classes/PermissionValidator_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/classes/ServiceScheduleModel.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls-meta.xml
  force-app/main/default/classes/TestUtil.cls
  force-app/main/default/classes/Util.cls
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/picklist/picklist.html
  force-app/main/default/lwc/picklist/picklist.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
Labels: in QE review

#297 Monthly Iterator
  force-app/main/default/classes/MonthlyIterator.cls
  force-app/main/default/classes/MonthlyIterator.cls-meta.xml
  force-app/main/default/classes/MonthlyIterator_TEST.cls
  force-app/main/default/classes/MonthlyIterator_TEST.cls-meta.xml
  force-app/main/default/classes/RecurrenceFactory.cls
  force-app/main/default/classes/RecurrenceFactory_TEST.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls
  force-app/main/default/classes/RecurrenceService.cls
  force-app/main/default/classes/RecurrenceService_TEST.cls
Labels: wip

#294 Communicate between screens (Screen 3)
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls
  force-app/main/default/classes/SelectParticipantController.cls
  force-app/main/default/classes/SelectParticipantController_TEST.cls
  force-app/main/default/classes/SelectParticipantModel.cls
  force-app/main/default/classes/SelectParticipantModel.cls-meta.xml
  force-app/main/default/classes/SelectParticipantService.cls
  force-app/main/default/classes/SelectParticipantService_TEST.cls
  force-app/main/default/classes/SelectParticipantService_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/ServiceScheduleDomain.cls
  force-app/main/default/classes/ServiceScheduleDomain.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
Labels: in dev review

#300 Move PE flow to the unpackaged folder
  cumulusci.yml
  unpackaged/config/dev/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
Labels: in QE review

#298 Group Services Schedule Wizard end-to-end!
  force-app/main/default/classes/FieldSetController.cls
  force-app/main/default/classes/FieldSetController_TEST.cls
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/classes/PermissionValidator.cls
  force-app/main/default/classes/PermissionValidator_TEST.cls
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/ProgramTestDataFactory.cls
  force-app/main/default/classes/RecurrenceRule.cls
  force-app/main/default/classes/RecurrenceRule_TEST.cls
  force-app/main/default/classes/SelectParticipantController.cls
  force-app/main/default/classes/SelectParticipantController_TEST.cls
  force-app/main/default/classes/SelectParticipantModel.cls
  force-app/main/default/classes/SelectParticipantModel.cls-meta.xml
  force-app/main/default/classes/SelectParticipantService.cls
  force-app/main/default/classes/SelectParticipantService_TEST.cls
  force-app/main/default/classes/SelectParticipantService_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/ServiceScheduleDomain.cls
  force-app/main/default/classes/ServiceScheduleDomain.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/ServiceSelector.cls
  force-app/main/default/classes/ServiceSelector_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
  force-app/main/default/objects/ProgramEngagement__c/fieldSets/SessionParticipantView.fieldSet-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fieldSets/ServiceScheduleInformation.fieldSet-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/Frequency__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/Status__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
Labels: in QE review

#303 Reorganize code; use custom iterator
  force-app/main/default/classes/DailyIterable.cls
  force-app/main/default/classes/DailyIterable.cls-meta.xml
  force-app/main/default/classes/DailyIterable_TEST.cls
  force-app/main/default/classes/DailyIterable_TEST.cls-meta.xml
  force-app/main/default/classes/DailyIterator.cls
  force-app/main/default/classes/MonthlyIterable.cls
  force-app/main/default/classes/MonthlyIterable.cls-meta.xml
  force-app/main/default/classes/MonthlyIterable_TEST.cls
  force-app/main/default/classes/MonthlyIterable_TEST.cls-meta.xml
  force-app/main/default/classes/MonthlyIterator.cls
  force-app/main/default/classes/RecurrenceFactory.cls
  force-app/main/default/classes/RecurrenceFactoryInterface.cls
  force-app/main/default/classes/RecurrenceFactory_TEST.cls
  force-app/main/default/classes/RecurrenceFactory_TEST.cls-meta.xml
  force-app/main/default/classes/RecurrenceIteratorInterface.cls
  force-app/main/default/classes/RecurrenceIteratorInterface.cls-meta.xml
  force-app/main/default/classes/RecurrenceService.cls
  force-app/main/default/classes/RecurrenceService_TEST.cls
  force-app/main/default/classes/WeeklyIterable.cls
  force-app/main/default/classes/WeeklyIterable.cls-meta.xml
  force-app/main/default/classes/WeeklyIterable_TEST.cls
  force-app/main/default/classes/WeeklyIterable_TEST.cls-meta.xml
  force-app/main/default/classes/WeeklyIterator.cls
  force-app/main/default/classes/WeeklyIterator.cls-meta.xml
  force-app/main/default/classes/WeeklyIterator_TEST.cls-meta.xml
Labels: ready to merge
