Repository SalesforceFoundation/PMM, pull requests merged in 2020-11, with the labels that each got.

#335 [Robot] Added test to create service session
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_50.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
  robot/pmm/tests/browser/ServiceParticipant/new_service_participant.robot
  robot/pmm/tests/browser/ServiceSession/new_service_session.robot
Labels: 🤖 test

#337 Add ServiceSession field to available BSDT field set
  .github/PULL_REQUEST_TEMPLATE.md
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Bulk_Service_Deliveries.fieldSet-meta.xml
Labels: in QE review

#333 Attendance Capture Backend
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController.cls-meta.xml
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/AttendanceController_TEST.cls-meta.xml
  force-app/main/default/classes/AttendanceSelector.cls
  force-app/main/default/classes/AttendanceSelector.cls-meta.xml
  force-app/main/default/classes/AttendanceSelector_TEST.cls
  force-app/main/default/classes/AttendanceSelector_TEST.cls-meta.xml
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService.cls-meta.xml
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/AttendanceService_TEST.cls-meta.xml
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/ProgramTestDataFactory.cls
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/ServiceSelector_TEST.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TestDataFactory.cls-meta.xml
  unpackaged/config/customer_profiles/profiles/Program Management Standard User.profile
Labels: ready to merge

#342 [Robot] Fix test failures and added cohort test
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ProgramPageObject.py
  robot/pmm/resources/ServiceDeliveryPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/ServiceParticipantPageObject.py
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/tests/browser/Program/add_service.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/Service/quickactions_service.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
  robot/pmm/tests/browser/ServiceParticipant/new_service_participant.robot
  robot/pmm/tests/browser/ServiceSession/new_service_session.robot
Labels: 🤖 test

#344 Attendance Commit
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/AttendanceSelector.cls
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/ServiceDeliveryDomain.cls
  force-app/main/default/classes/ServiceDeliveryDomain.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls
  force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/attendance/attendance.html
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendanceRow/__mocks__/attendanceRow.js
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
Labels: in dev review

#347 Reduce padding on BSDT row cards
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/staticresources/pmm/bsdtOverrides.css
Labels: ready for QE

#343 Feature/attendance recent sessions on home page
  force-app/main/default/classes/RecentServiceSessionController.cls
  force-app/main/default/classes/RecentServiceSessionController.cls-meta.xml
  force-app/main/default/classes/RecentServiceSessionController_TEST.cls
  force-app/main/default/classes/RecentServiceSessionController_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/classes/ServiceSessionSelector.cls-meta.xml
  force-app/main/default/classes/ServiceSessionSelector_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceSessionService.cls
  force-app/main/default/classes/ServiceSessionService.cls-meta.xml
  force-app/main/default/classes/ServiceSessionService_TEST.cls
  force-app/main/default/classes/ServiceSessionService_TEST.cls-meta.xml
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/flexipages/Program_Management_Home.flexipage-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/accordionSection/accordionSection.html
  force-app/main/default/lwc/accordionSection/accordionSection.js
  force-app/main/default/lwc/accordionSection/accordionSection.js-meta.xml
  force-app/main/default/lwc/recentSessions/recentSessions.css
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/recentSessions/recentSessions.js-meta.xml
  force-app/main/default/lwc/util/util.js
  force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
Labels: in QE review

#339 Use Field Set for Participant Selector on New Service Schedule
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/SelectParticipantModel.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
Labels: in QE review, ready to merge

#349 Recent sessions component UI fixes
  force-app/main/default/classes/AttendanceSelector_TEST.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/RecentServiceSessionController.cls
  force-app/main/default/classes/RecentServiceSessionController_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/classes/ServiceSessionSelector_TEST.cls
  force-app/main/default/classes/ServiceSessionService_TEST.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/accordionSection/accordionSection.css
  force-app/main/default/lwc/recentSessions/recentSessions.css
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/sessionCard/sessionCard.html
  force-app/main/default/lwc/sessionCard/sessionCard.js
  force-app/main/default/lwc/sessionCard/sessionCard.js-meta.xml
  force-app/main/default/lwc/skipLinks/skipLinks.css
  force-app/main/default/lwc/skipLinks/skipLinks.html
  force-app/main/default/lwc/skipLinks/skipLinks.js
  force-app/main/default/lwc/skipLinks/skipLinks.js-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
Labels: ready for QE

#351 Default Service Quantity support for schedules and attendance
  force-app/main/default/classes/AttendanceSelector.cls
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/participantSelector/participantSelector.css
  force-app/main/default/objects/ServiceSchedule__c/fieldSets/ServiceScheduleInformation.fieldSet-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/DefaultServiceQuantity__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review

#346 Always show BSDT footer, styled BSDT modal
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/modal/modal.html
  force-app/main/default/lwc/modal/modal.js
  force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.html
  force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/staticresources/pmm/bsdtOverrides.css
Labels: in QE review

#350 Feature/date defaults
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/Util.cls
  force-app/main/default/lwc/futureSessionDeleter/futureSessionDeleter.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/picklist/picklist.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/objects/ServiceSchedule__c/fields/FirstSessionStart__c.field-meta.xml
Labels: in QE review

#356 Support for sessions that span multiple days
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.css
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
Labels: in QE review

#357 [Robot] Test to create new service schedule using wizard
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ServiceParticipantPageObject.py
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_50.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
  robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
Labels: 🤖 test

#355 Attendance FLS check + empty state
  .labelauditignore.json
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/PermissionValidator.cls
  force-app/main/default/classes/PermissionValidator_TEST.cls
  force-app/main/default/classes/PermissionValidator_TEST.cls-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/attendance/__tests__/attendance.test.js
  force-app/main/default/lwc/attendance/__tests__/data/wiredNoPermissions.json
  force-app/main/default/lwc/attendance/__tests__/data/wiredPendingSession.json
  force-app/main/default/lwc/attendance/__tests__/data/wiredPermissions.json
  force-app/main/default/lwc/attendance/attendance.html
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/emptyState/emptyState.html
  force-app/main/default/lwc/emptyState/emptyState.js
  force-app/main/default/lwc/emptyState/emptyState.js-meta.xml
  force-app/main/default/lwc/scopedNotification/scopedNotification.js
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Bulk_Service_Deliveries.fieldSet-meta.xml
Labels: in dev review

#361 [Robot] Add/remove service participants on screen3
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/locators_50.py
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
Labels: 🤖 test

#365 Add 'Every N Days/Weeks/Months' options to Service Schedule Wizard
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/objects/ServiceSchedule__c/fields/Interval__c.field-meta.xml
Labels: in QE review
