Repository SalesforceFoundation/PMM, pull requests merged in 2020-05, with the labels that each got.

#200 FieldSetController fix
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
Labels: ready to merge

#197 Fix for incorrect done button title
  .forceignore
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
Labels: ready to merge

#145 Robot test to create prog engagement from bsdt
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm.robot
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/create_prog_engagement.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/Program/quick_actions.robot
  robot/pmm/tests/browser/Program/service.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
Labels: 🤖 test

#191 Fix filter on client records with missing phone number
  force-app/main/default/reports/ProgramManagementReports/Client_Records_with_Missing_Phone_Number.report-meta.xml
Labels: in QE review

#190 Remove scrolling on BSDT to fix date popup
  force-app/main/default/staticresources/pmm/bsdtOverrides.css
Labels: in QE review

#192 Add Telemetry Count for Active Programs with Program Engagements
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/InstallScript_TEST.cls
  force-app/main/default/classes/QueryBuilder.cls
  force-app/main/default/classes/QueryBuilder_TEST.cls
  force-app/main/default/featureParameters/ActiveProgramsWithEngagementsLast30.featureParameterInteger-meta.xml
Labels: no QE needed

#204 remove duplicate populate form keywords
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ContactPageObject.py
  robot/pmm/resources/ProgramCohortPageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ProgramPageObject.py
  robot/pmm/resources/ServiceDeliveryPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/create_prog_engagement.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/Program/quick_actions.robot
  robot/pmm/tests/browser/Program/service.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
Labels: ready to merge, 🤖 test

#206 Removed enrolled stage from process builder
  force-app/main/default/flows/Auto_Populate_Date_And_Name_On_Program_Engagement.flow-meta.xml
Labels: in QE review

#209 Change object icons
  force-app/main/default/tabs/Bulk_Service_Deliveries.tab-meta.xml
  force-app/main/default/tabs/ProgramCohort__c.tab-meta.xml
  force-app/main/default/tabs/Program__c.tab-meta.xml
  force-app/main/default/tabs/ServiceDelivery__c.tab-meta.xml
  force-app/main/default/tabs/Service__c.tab-meta.xml
Labels: in QE review

#205 Telemetry: Service Deliveries created with active programs in last 30 days
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/ProgramTestDataFactory.cls
  force-app/main/default/featureParameters/ActiveProgramsWithServiceDeliveriesLast30.featureParameterInteger-meta.xml
Labels: ready to merge

#212 Make label audit blocking, update script with improvements from caseman
  .github/PULL_REQUEST_TEMPLATE.md
  .labelauditignore.json
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.js
  label_audit.py
  requirements.txt
Labels: ready for review

#210 BSDT UX tweaks: adjust field widths and use UOM for Quantity label
  force-app/main/default/classes/FieldSetController.cls
  force-app/main/default/classes/FieldSetController_TEST.cls
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/classes/ServiceDeliveryController.cls
  force-app/main/default/classes/ServiceDeliveryController_TEST.cls
  force-app/main/default/classes/ServiceService.cls
  force-app/main/default/classes/ServiceService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Default.fieldSet-meta.xml
Labels: in QE review

#211 Namespace prefix for robot tests
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ProgramCohortPageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ProgramPageObject.py
  robot/pmm/resources/ServiceDeliveryPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm.robot
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/create_prog_engagement.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/Program/quick_actions.robot
  robot/pmm/tests/browser/Program/service.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
Labels: 🤖 test

#217 quick actions on contact
  robot/pmm/doc/Keywords.html
  robot/pmm/tests/browser/Contact/quickactions.robot
  robot/pmm/tests/browser/Program/add_service.robot
  robot/pmm/tests/browser/Program/pe_quickaction.robot
Labels: 🤖 test
