Repository SalesforceFoundation/PMM, pull requests merged in 2020-07, with the labels that each got.

#241 Add Waitlisted Program Engagements List View
  force-app/main/default/objectTranslations/Service__c-de/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-en_GB/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-es/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-es_MX/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-fr/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-fr_CA/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-ja/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-nl_NL/Status__c.fieldTranslation-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/listViews/WaitlistedProgramEngagements.listView-meta.xml
  force-app/main/default/objects/Service__c/fields/Status__c.field-meta.xml
Labels: in QE review

#243 Remove client as required field from program engagement fieldset
  force-app/main/default/objects/ProgramEngagement__c/fieldSets/CreateProgramEngagement.fieldSet-meta.xml
Labels: in QE review

#245 Auto populate contact
  cumulusci.yml
  force-app/main/default/quickActions/ProgramEngagement__c.CreateServiceDelivery.quickAction-meta.xml
Labels: in QE review

#248 Update unpackaged report chart
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Service_Deliveries_by_Provider_LastMonth_PEO.report
Labels: in QE review

#244 Special handling of various field types
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Default.fieldSet-meta.xml
Labels: in QE review

#246 Handle namespace injection in packaging org
  .forceignore
  cumulusci.yml
Labels: ready for review

#242 [Robot] added tests for validation rules on SD
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ServiceDeliveryPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm.robot
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/create_prog_engagement.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Contact/quickactions.robot
  robot/pmm/tests/browser/Program/add_service.robot
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/Program/pe_quickaction.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/Service/quickactions_service.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
Labels: 🤖 test

#251 [Robot] Test to validate cohort and PE lookup to same program
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Program/pe_quickaction.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/ServiceDeliveries/new_service_delivery.robot
Labels: 🤖 test

#253 Update report descriptions and flexipage label
  force-app/main/default/flexipages/Contact_Record_Page.flexipage-meta.xml
  force-app/main/default/reports/ProgramManagementReports/All_Active_Program_Engagements_HWv.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Client_Records_with_Missing_Phone_Number.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Clients_Enrolled_This_Month_6ez.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Clients_Enrolled_This_Month_by_Program_Nk9.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Services_Delivered_Year_to_Date_MY.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Units_Delivered_over_last_6_Months_3DR.report-meta.xml
Labels: in QE review

#254 Add program engagement by owner report
  unpackaged/post/reports/package.xml
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Enrolled_Active_Prog_Eng_by_Owner_JZY.report
Labels: in QE review

#252 Add Feature Parameters to Count Permission Set Assignments
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/featureParameters/PermSetDeliverUsers.featureParameterInteger-meta.xml
  force-app/main/default/featureParameters/PermSetManageUsers.featureParameterInteger-meta.xml
Labels: ready for QE

#260 [Robot] Auto-populate fields on PE
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm_locators.py
  robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
Labels: 🤖 test
