Repository SalesforceFoundation/PMM, pull requests merged in 2021-03, with the labels that each got.

#418 [Robot] Robot test for Service Schedule wizard Screen1 validations
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/locators_51.py
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen1.robot
Labels: 🤖 test

#434 Last Service Date bug fix, add Consecutive Absences to page layouts
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
Labels: in QE review

#441 Rollup reports
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/CurrentUserOwner__c.field-meta.xml
  force-app/main/default/reportTypes/Contacts_with_and_without_Program_Engagements.reportType-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Contacts_Absent_for_Last_Svc_Delivery_qwd.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Contacts_with_3_Consecutive_Absences_p3K.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Contacts_wo_Recent_Service_Deliveries_2SV.report-meta.xml
Labels: in QE review

#442 Set Service Delivery defaults based on fields from selected service field set value
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
  force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.html
  force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js
  force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js-meta.xml
  force-app/main/default/lwc/visualPicker/visualPicker.css
  force-app/main/default/lwc/visualPicker/visualPicker.html
  force-app/main/default/objects/Service__c/fields/BulkServiceDeliveryFieldSet__c.field-meta.xml
  force-app/main/default/staticresources/pmm/bsdtOverrides.css
Labels: in dev review, ready for review, 🍼⟶ 👪 (no QE)

#438 Batch rollup calculations
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/ContactRollupsSchedulable.cls
  force-app/main/default/classes/ContactRollupsSchedulable.cls-meta.xml
  force-app/main/default/classes/ContactRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ContactRollupsSchedulable_TEST.cls-meta.xml
  force-app/main/default/classes/CustomMetadataSelector.cls
  force-app/main/default/classes/CustomMetadataSelector.cls-meta.xml
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable.cls
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable.cls-meta.xml
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/classes/ServiceRollupsSchedulable.cls
  force-app/main/default/classes/ServiceRollupsSchedulable.cls-meta.xml
  force-app/main/default/classes/ServiceRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ServiceRollupsSchedulable_TEST.cls-meta.xml
  force-app/main/default/classes/SessionRollupsSchedulable.cls
  force-app/main/default/classes/SessionRollupsSchedulable.cls-meta.xml
  force-app/main/default/classes/SessionRollupsSchedulable_TEST.cls
  force-app/main/default/classes/SessionRollupsSchedulable_TEST.cls-meta.xml
  force-app/main/default/classes/SystemAccess.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/classes/TestUtil.cls
  scripts/copyright.py
Labels: in QE review

#444 Add Participants Screen on BSDT Wizard
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
  force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.html
  force-app/main/default/lwc/groupServiceDelivery/groupServiceDelivery.js
  force-app/main/default/lwc/participantAdder/participantAdder.html
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/visualPicker/visualPicker.html
Labels: in dev review

#445 BSDT Manual Save
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/serviceDeliveryModal/serviceDeliveryModal.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: in QE review

#448 Add/Add All buttons for Participant Selector
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
Labels: in QE review

#439 [Robot] Added tests for PMM homepage
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/HomePageObject.py
  robot/pmm/resources/locators_51.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/Attendance/dim_attendance.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
  robot/pmm/tests/browser/HomePage/homepage_components.robot
  robot/pmm/tests/browser/HomePage/homepage_reports.robot
  robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
Labels: 🤖 test

#453 BSDT Wizard Final Touches
  force-app/main/default/classes/FieldSetController.cls
  force-app/main/default/classes/FieldSetController_TEST.cls
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/bulkServiceDeliveryUI/serviceDeliveryFieldSets.js
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.html
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js-meta.xml
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in dev review

#454 Seed group BSDT rows with selected participants and defaults
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/bulkServiceDeliveryUI/serviceDeliveryFieldSets.js
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.html
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: ready for review

#456 [Robot] Verify Programs listview, create new SD using quick action button
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/ServiceDeliveries/sd_quickaction.robot
Labels: 🤖 test

#437 WIP: BSDT Wizard
  force-app/main/default/classes/FieldSetController.cls
  force-app/main/default/classes/FieldSetController_TEST.cls
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.html
  force-app/main/default/lwc/bulkServiceDeliveryUI/bulkServiceDeliveryUI.js
  force-app/main/default/lwc/bulkServiceDeliveryUI/serviceDeliveryFieldSets.js
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.html
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js
  force-app/main/default/lwc/groupServiceDeliveries/groupServiceDeliveries.js-meta.xml
  force-app/main/default/lwc/navigationItems/navigationItems.js
  force-app/main/default/lwc/navigationItems/navigationItems.js-meta.xml
  force-app/main/default/lwc/participantAdder/participantAdder.html
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/progressSteps/progressStep.js
  force-app/main/default/lwc/progressSteps/progressSteps.js
  force-app/main/default/lwc/progressSteps/progressSteps.js-meta.xml
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.html
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js-meta.xml
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/visualPicker/visualPicker.css
  force-app/main/default/lwc/visualPicker/visualPicker.html
  force-app/main/default/lwc/visualPicker/visualPicker.js
  force-app/main/default/lwc/visualPicker/visualPicker.js-meta.xml
  force-app/main/default/objects/Service__c/fields/ServiceDeliveryFieldSet__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
  force-app/main/default/staticresources/pmm/bsdtOverrides.css
Labels: in QE review
