Repository SalesforceFoundation/PMM, pull requests merged in 2021-01, with the labels that each got.

#389 Allow encryption on all possible fields and note when not possible
  force-app/main/default/classes/ProgramEngagementSelector_TEST.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/ServiceSelector_TEST.cls
  lib/admin_profile.xml
  unencryptable.yml
Labels: ready for review

#388 [Robot] Added test to update attendance records
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_50.py
  robot/pmm/resources/pmm.robot
  robot/pmm/tests/browser/Attendance/dim_attendance.robot
  robot/pmm/tests/browser/Attendance/update_attendance.robot
Labels: 🤖 test

#391 Update Package Versions
  package.json
  yarn.lock
Labels: ready to merge

#392 Update search layout fields and compact layouts
  force-app/main/default/objects/ProgramCohort__c/ProgramCohort__c.object-meta.xml
  force-app/main/default/objects/ProgramCohort__c/compactLayouts/ProgramCohortCompactLayout.compactLayout-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/ProgramEngagement__c.object-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/compactLayouts/ProgramEngagementCompactLayout.compactLayout-meta.xml
  force-app/main/default/objects/Program__c/Program__c.object-meta.xml
  force-app/main/default/objects/Program__c/compactLayouts/ProgramCompactLayout.compactLayout-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/ServiceDelivery__c.object-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/compactLayouts/ServiceDeliveryCompactLayout.compactLayout-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/ServiceSchedule__c.object-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/compactLayouts/ServiceScheduleCompactLayout.compactLayout-meta.xml
  force-app/main/default/objects/Service__c/Service__c.object-meta.xml
  force-app/main/default/objects/Service__c/compactLayouts/ServiceCompactLayout.compactLayout-meta.xml
Labels: in QE review

#393 [Robot] added test for service participant quick action
  robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
Labels: 🤖 test

#394 Robot: Empty state on Track Attendance component
  robot/pmm/tests/browser/Attendance/empty_attendance.robot
Labels: 🤖 test

#395 [Robot] updated auto-populate tests on PE
  robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
Labels: 🤖 test

#397 Add Attendance storytelling data
  datasets/mapping.yml
  datasets/sample.sql
Labels: ready for review

#398 Move missing tab fix to master
  lib/admin_profile.xml
Labels: in QE review

#400 2 new unpackaged Reports
  unpackaged/post/reports/package.xml
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Pending_Sessions_in_Past_by_Provider_jZH.report
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Unique_Contacts_Receiving_Service_Year_t_44q.report
Labels: in QE review

#402 [Robot] Test updates for prerelease orgs
  robot/pmm/doc/Keywords.html
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ContactPageObject.py
  robot/pmm/resources/ServicePageObject.py
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_49.py
  robot/pmm/resources/locators_50.py
  robot/pmm/resources/locators_51.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/Attendance/dim_attendance.robot
  robot/pmm/tests/browser/Attendance/update_attendance.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/Add_service_deliveries.robot
  robot/pmm/tests/browser/Bulk_Service_Delivery/add_pe_on_BSDT.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Contact/quickactions.robot
  robot/pmm/tests/browser/Program/add_service.robot
  robot/pmm/tests/browser/Program/pe_quickaction.robot
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/quickactions_service.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
Labels: 🤖 test
