Repository SalesforceFoundation/PMM, pull requests merged in 2021-06, with the labels that each got.

#488 Displaying unique contact count on caseman dashboard
  force-app/main/default/reports/ProgramManagementReports/Contacts_Absent_for_Last_Svc_Delivery_qwd.report-meta.xml
  force-app/main/default/reports/ProgramManagementReports/Contacts_with_3_Consecutive_Absences_p3K.report-meta.xml
Labels: in QE review

#486 [Robot] added test for attendance calculations
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_51.py
  robot/pmm/resources/pmm.py
  robot/pmm/resources/pmm.robot
  robot/pmm/tests/browser/Attendance/attendance_summary.robot
  robot/pmm/tests/browser/Attendance/dim_attendance.robot
  robot/pmm/tests/browser/Attendance/update_attendance.robot
Labels: 🤖 test

#487 added attendance status field to related list
  force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/layouts/Service__c-Service Layout.layout-meta.xml
Labels: in QE review

#491 Updated Storytelling Data
  datasets/mapping.yml
  datasets/sample.sql
Labels: in QE review

#484 Incremental Trigger Rollups
  force-app/main/default/classes/ContactRollupsSchedulable.cls
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable.cls
  force-app/main/default/classes/RollupRecord.cls
  force-app/main/default/classes/RollupRecord_TEST.cls
  force-app/main/default/classes/ServiceDelivery.cls
  force-app/main/default/classes/ServiceDelivery.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryRollupsBatch.cls
  force-app/main/default/classes/ServiceDeliveryRollupsService.cls
  force-app/main/default/classes/ServiceDeliveryRollupsService_TEST.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/classes/ServiceRollupsSchedulable.cls
  force-app/main/default/classes/SessionRollupsSchedulable.cls
  force-app/main/default/classes/SystemAccess.cls
  force-app/main/default/classes/TestUtil.cls
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToContact.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToProgramEngagement.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToService.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToServiceSession.md-meta.xml
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: in QE review

#497 Fix error on Service Schedule Wizard when in Lightning Debug Mode and Fix error when attempting to load more than 50000 related Program Engagements
  force-app/main/default/classes/ProgramEngagementSelector.cls
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/lwc/loadingStencil/__tests__/loadingStencil.test.js
  force-app/main/default/lwc/loadingStencil/loadingStencil.css
  force-app/main/default/lwc/loadingStencil/loadingStencil.html
  force-app/main/default/lwc/loadingStencil/loadingStencil.js
  force-app/main/default/lwc/loadingStencil/loadingStencil.js-meta.xml
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/picklist/picklist.js
Labels: in QE review

#499 [Robot] Added/updated service schedule tests
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/resources/ContactPageObject.py
  robot/pmm/resources/HomePageObject.py
  robot/pmm/resources/ProgramEngagementPageObject.py
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_51.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen2.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
Labels: 🤖 test

#502 Add community login button to Contact layout
  cumulusci.yml
Labels: in dev review

#500 [Robot] SessionParticipantview fieldset
  cumulusci.yml
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/locators_49.py
  robot/pmm/resources/locators_50.py
  robot/pmm/resources/locators_51.py
  robot/pmm/resources/locators_52.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/Attendance/attendance_summary.robot
  robot/pmm/tests/browser/Contact/create_contact.robot
  robot/pmm/tests/browser/Contact/quickactions.robot
  robot/pmm/tests/browser/Program/add_service.robot
  robot/pmm/tests/browser/Program/create_program.robot
  robot/pmm/tests/browser/Program/pe_quickaction.robot
  robot/pmm/tests/browser/ProgramEngagement/ProgramEngagement.robot
  robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
  robot/pmm/tests/browser/ProgramEngagement/quick_actions_sd.robot
  robot/pmm/tests/browser/Service/new_service.robot
  robot/pmm/tests/browser/Service/quickactions_service.robot
  robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen2.robot
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_screen3.robot
  sfdx-project.json
  unpackaged/config/cmdts/customMetadata/___NAMESPACE___FeatureGate.___NAMESPACE___ServiceDeliveriesToContact.md-meta.xml
  unpackaged/config/cmdts/customMetadata/___NAMESPACE___FeatureGate.___NAMESPACE___ServiceDeliveriesToProgramEngagement.md-meta.xml
  unpackaged/config/cmdts/customMetadata/___NAMESPACE___FeatureGate.___NAMESPACE___ServiceDeliveriesToService.md-meta.xml
  unpackaged/config/cmdts/customMetadata/___NAMESPACE___FeatureGate.___NAMESPACE___ServiceDeliveriesToServiceSession.md-meta.xml
Labels: 🤖 test
