Repository SalesforceFoundation/PMM, pull requests merged in 2021-08, with the labels that each got.

#527 Add active services telemetry
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/featureParameters/ActiveServices.featureParameterInteger-meta.xml
Labels: ready for QE

#530 Mass create PE's from contact list views
  unpackaged/config/dev/objects/Contact.object-meta.xml
  unpackaged/config/dev/package.xml
Labels: ready to merge

#531 Added new button on PE related list
  force-app/main/default/layouts/ProgramCohort__c-Program Cohort Layout.layout-meta.xml
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
Labels: ready to merge

#528 Add active programs with active services telemetry
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/featureParameters/ActiveProgramsWithActiveServices.featureParameterInteger-meta.xml
Labels: ready for QE

#529 Added telemetry for active Programs with Program Cohorts
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/featureParameters/ActiveProgramsWithCohorts.featureParameterInteger-meta.xml
Labels: ready for QE

#536 Telemetry for active services with service schedules
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/featureParameters/ActiveServicesWithServiceSchedules.featureParameterInteger-meta.xml
Labels: in QE review

#540 New Program Engagement modal: New Contact layer
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.css
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.html
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/objects/Contact/fieldSets/CreateContact.fieldSet-meta.xml
Labels: in QE review
