Repository SalesforceFoundation/PMM, pull requests merged in 2021-05, with the labels that each got.

#474 [Robot] Manual Save on BSDT
  robot/pmm/resources/BulkServiceDeliveryPageObject.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/individual_service_delivery.robot
Labels: 🤖 test

#476 Fix for count calculation on Recent Sessions
  force-app/main/default/lwc/recentSessions/recentSessions.js
Labels: in QE review

#473 Make New Service Schedule work in Experience Cloud
  force-app/main/default/aura/createServiceSchedule/createServiceSchedule.cmp
  force-app/main/default/aura/createServiceSchedule/createServiceScheduleController.js
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/__tests__/serviceScheduleCreatorWrapper.test.js
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.html
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.js
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.js-meta.xml
Labels: in QE review

#477 Add newly-not-required fields to perm sets
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review

#472 LDV'ify Batch Process
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/ContactRollupsSchedulable.cls
  force-app/main/default/classes/ContactRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable.cls
  force-app/main/default/classes/ProgramEngagementRollupsSchedulable_TEST.cls
  force-app/main/default/classes/RollupRecord.cls
  force-app/main/default/classes/RollupRecord.cls-meta.xml
  force-app/main/default/classes/RollupRecord_TEST.cls
  force-app/main/default/classes/RollupRecord_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryRollupsBatch.cls
  force-app/main/default/classes/ServiceDeliveryRollupsBatch.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryRollupsService.cls
  force-app/main/default/classes/ServiceDeliveryRollupsService.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryRollupsService_TEST.cls
  force-app/main/default/classes/ServiceDeliveryRollupsService_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceDeliverySelector.cls
  force-app/main/default/classes/ServiceDeliverySelector.cls-meta.xml
  force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
  force-app/main/default/classes/ServiceDeliverySelector_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryService.cls
  force-app/main/default/classes/ServiceDeliveryService.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryService_TEST.cls
  force-app/main/default/classes/ServiceDeliveryService_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/classes/ServiceRollupsSchedulable.cls
  force-app/main/default/classes/ServiceRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ServiceService_TEST.cls
  force-app/main/default/classes/SessionRollupsSchedulable.cls
  force-app/main/default/classes/SessionRollupsSchedulable_TEST.cls
  force-app/main/default/classes/Stub.cls
  force-app/main/default/classes/StubBuilder.cls
  force-app/main/default/classes/SystemAccess.cls
  force-app/main/default/classes/SystemAccess_TEST.cls
  force-app/main/default/classes/TestDataFactory.cls
Labels: ready to merge

#480 Attendance summary on recent service session component
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/sessionCard/sessionCard.html
  force-app/main/default/lwc/sessionCard/sessionCard.js
  force-app/main/default/objects/ServiceSession__c/fieldSets/RecentSessionsView.fieldSet-meta.xml
Labels: in QE review

#482 [Robot] Feature/robot bsdt filter
  robot/pmm/resources/locators_51.py
  robot/pmm/tests/browser/Bulk_Service_Delivery/group_service_delivery.robot
Labels: 🤖 test
