Repository SalesforceFoundation/PMM, pull requests merged in 2021-09, with the labels that each got.

#541 Final adjustments and fixes on New Program Engagement modal
  force-app/main/default/classes/ProgramController.cls
  force-app/main/default/classes/ProgramController_TEST.cls
  force-app/main/default/lwc/attendance/__tests__/attendance.test.js
  force-app/main/default/lwc/formattedField/__tests__/formattedField.test.js
  force-app/main/default/lwc/listViewSelector/__tests__/listViewSelector.test.js
  force-app/main/default/lwc/loadingStencil/__tests__/loadingStencil.test.js
  force-app/main/default/lwc/modal/__tests__/modal.test.js
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getFieldSet.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getFieldSetByObjectKey.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getObjectInfo.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getPicklistValues.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/data/getProgramCohortsFromProgramId.json
  force-app/main/default/lwc/newProgramEngagement/__tests__/newProgramEngagement.test.js
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.css
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.html
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.js
  force-app/main/default/lwc/participantSelector/participantSelector.html
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/scopedNotification/__tests__/scopedNotification.test.js
  force-app/main/default/lwc/serviceScheduleCreator/__tests__/serviceScheduleCreator.test.js
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/__tests__/serviceScheduleCreatorWrapper.test.js
  jest.setup.js
Labels: ready for review

#542 Fix double scroll bar on New Program Engagement
  force-app/main/default/lwc/modal/modal.html
  force-app/main/default/lwc/modal/modal.js
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.css
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.html
  force-app/main/default/lwc/newProgramEngagement/newProgramEngagement.js
Labels: ready for QE

#543 Removing duplicate entries in participant selector
  force-app/main/default/lwc/participantSelector/participantSelector.js
Labels: ready for QE

#547 [Robot] Fixed unstable tests
  robot/pmm/tests/browser/ProgramCohort/Create_Program_Cohort.robot
  robot/pmm/tests/browser/ProgramEngagement/autopopulate_pe_fields.robot
Labels: 🤖 test, in dev review
