Repository SalesforceFoundation/PMM, pull requests merged in 2021-07, with the labels that each got.

#511 Dependabot 232.1
  package.json
  yarn.lock
Labels: ready for review

#510 [Robot] Delete future service sessions
  robot/pmm/resources/pmm.robot
  robot/pmm/tests/browser/ServiceSchedule/delete_future_sessions.robot
Labels: 🤖 test

#515 [Robot] Update fields on attendance service deliveries fieldset
  robot/pmm/resources/ServiceSessionPageObject.py
  robot/pmm/resources/locators_52.py
  robot/pmm/tests/browser/Attendance/update_attendance.robot
Labels: 🤖 test

#520 [Robot] Validate message on Attendance tab
  robot/pmm/resources/locators_52.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/Attendance/attendance_tab.robot
Labels: 🤖 test

#521 Fix name of attendance feature parameter.
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
Labels: ready for review

#519 Formula Updates for Attendance
  force-app/main/default/objects/Contact/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/Contact/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/AttendanceSummary__c.field-meta.xml
Labels: in QE review

#523 Add data before push upgrading beta
  cumulusci.yml
Labels: ready for review

#522 Reduce the number of query rows needed for telemetry
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/ServiceDeliveryRollupsService.cls
  force-app/main/default/classes/Util.cls
Labels: ready to merge

#526 [Robot] Switch fieldsets on bsdt
  robot/pmm/tests/browser/Bulk_Service_Delivery/bsdt_fieldsets.robot
Labels: 🤖 test
