Repository SalesforceFoundation/PMM, pull requests merged in 2021-02, with the labels that each got.

#403 Update report name
  unpackaged/post/reports/package.xml
  unpackaged/post/reports/reports/ProgramManagementReportsUnpackaged/Past_Sessions_in_Pending_Status_jZH.report
Labels: in QE review

#405 Update description of stage field on program engagement
  force-app/main/default/objects/ProgramEngagement__c/fields/Stage__c.field-meta.xml
Labels: in QE review

#404 Scope css to recent sessions component
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/staticresources/pmm/recentSessionsOverrides.css
Labels: in QE review

#408 Add additional field options to packaged field sets
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/objects/ProgramEngagement__c/fieldSets/SessionParticipantView.fieldSet-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/fieldSets/Attendance_Service_Deliveries.fieldSet-meta.xml
  force-app/main/default/objects/ServiceSession__c/fieldSets/RecentSessionsView.fieldSet-meta.xml
Labels: in QE review

#413 Bug Fixes for Service Schedule Debounce and CSS
  force-app/main/default/lwc/attendance/attendance.html
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
Labels: in QE review

#415 Attendance Status/Service Delivery records created in last 30 days
  force-app/main/default/classes/FeatureParameters.cls
  force-app/main/default/classes/FeatureParameters_TEST.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/featureParameters/AttendanceServiceDeliveriesLast30.featureParameterInteger-meta.xml
Labels: ready for review

#409 Attendance Rollup Fields
  force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
  force-app/main/default/objects/Contact/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/Contact/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/Contact/fields/LastServiceDate__c.field-meta.xml
  force-app/main/default/objects/Contact/fields/NumAbsentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/Contact/fields/NumPresentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/LastServiceDate__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/ServiceSession__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/Service__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review

#414 Service Delivery trigger and handler framework, FeatureGate custom metadata, BucketedField custom metadata
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls-meta.xml
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls-meta.xml
  force-app/main/default/customMetadata/FeatureGate.AttendanceToContact.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.AttendanceToProgramEngagement.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.AttendanceToService.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.AttendanceToServiceSession.md-meta.xml
  force-app/main/default/layouts/Bucket__mdt-Bucket Layout.layout-meta.xml
  force-app/main/default/layouts/BucketedField__mdt-Bucketed Field Layout.layout-meta.xml
  force-app/main/default/layouts/BucketedValue__mdt-Bucketed Value Layout.layout-meta.xml
  force-app/main/default/layouts/FeatureGate__mdt-Feature Gate Layout.layout-meta.xml
  force-app/main/default/objects/Bucket__mdt/Bucket__mdt.object-meta.xml
  force-app/main/default/objects/Bucket__mdt/fields/BucketedField__c.field-meta.xml
  force-app/main/default/objects/BucketedField__mdt/BucketedField__mdt.object-meta.xml
  force-app/main/default/objects/BucketedField__mdt/fields/Field__c.field-meta.xml
  force-app/main/default/objects/BucketedField__mdt/fields/Object__c.field-meta.xml
  force-app/main/default/objects/BucketedValue__mdt/BucketedValue__mdt.object-meta.xml
  force-app/main/default/objects/BucketedValue__mdt/fields/Bucket__c.field-meta.xml
  force-app/main/default/objects/BucketedValue__mdt/fields/Value__c.field-meta.xml
  force-app/main/default/objects/FeatureGate__mdt/FeatureGate__mdt.object-meta.xml
  force-app/main/default/objects/FeatureGate__mdt/fields/FeatureActive__c.field-meta.xml
  force-app/main/default/objects/FeatureGate__mdt/listViews/Active.listView-meta.xml
  force-app/main/default/triggers/ServiceDeliveryTrigger.trigger
  force-app/main/default/triggers/ServiceDeliveryTrigger.trigger-meta.xml
Labels: ready to merge

#419 Date localization fix in Recent Sessions cmp
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
Labels: in QE review

#423 Feature/230 final 230 translations
  force-app/main/default/objectTranslations/ServiceDelivery__c-de/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-en_GB/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-es/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-es_MX/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-fr/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-ja/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceDelivery__c-nl_NL/AttendanceStatus__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-de/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-de/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-de/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-de/ServiceSchedule__c-de.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-en_GB/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-en_GB/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-en_GB/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-en_GB/ServiceSchedule__c-en_GB.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es/ServiceSchedule__c-es.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es_MX/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es_MX/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es_MX/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-es_MX/ServiceSchedule__c-es_MX.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-fr/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-fr/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-fr/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-fr/ServiceSchedule__c-fr.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-ja/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-ja/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-ja/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-ja/ServiceSchedule__c-ja.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-nl_NL/CreateServiceSessionRecords__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-nl_NL/DefaultServiceQuantity__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-nl_NL/MonthlyRecurrenceOption__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSchedule__c-nl_NL/ServiceSchedule__c-nl_NL.objectTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-de/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-en_GB/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-es/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-es_MX/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-fr/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-ja/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/ServiceSession__c-nl_NL/ServiceLink__c.fieldTranslation-meta.xml
  force-app/main/default/objectTranslations/Service__c-fr_CA/Status__c.fieldTranslation-meta.xml
  force-app/main/default/translations/de.translation-meta.xml
  force-app/main/default/translations/en_GB.translation-meta.xml
  force-app/main/default/translations/es.translation-meta.xml
  force-app/main/default/translations/es_MX.translation-meta.xml
  force-app/main/default/translations/fr.translation-meta.xml
  force-app/main/default/translations/ja.translation-meta.xml
  force-app/main/default/translations/nl_NL.translation-meta.xml
  metadeploy/labels_de.json
  metadeploy/labels_en-GB.json
  metadeploy/labels_es-MX.json
  metadeploy/labels_es.json
  metadeploy/labels_fr.json
  metadeploy/labels_ja.json
  metadeploy/labels_nl.json
Labels: ready for review

#429 Consecutive Absences and Last Service Date fields population
  cumulusci.yml
  force-app/main/default/classes/AttendanceSelector.cls
  force-app/main/default/classes/AttendanceService.cls
  force-app/main/default/classes/AttendanceService_TEST.cls
  force-app/main/default/classes/AttendanceSystemAccess.cls
  force-app/main/default/classes/QueryBuilder.cls
  force-app/main/default/classes/QueryBuilder_TEST.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler.cls
  force-app/main/default/classes/ServiceDeliveryTriggerHandler_TEST.cls
  force-app/main/default/classes/SystemAccess.cls
  force-app/main/default/classes/SystemAccess.cls-meta.xml
  force-app/main/default/classes/SystemAccess_TEST.cls
  force-app/main/default/classes/SystemAccess_TEST.cls-meta.xml
  force-app/main/default/classes/TestDataFactory.cls
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToContact.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToProgramEngagement.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToService.md-meta.xml
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToServiceSession.md-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/Contact-Program Management.layout-meta.xml
  force-app/main/default/layouts/ProgramEngagement__c-Program Engagement Layout.layout-meta.xml
  force-app/main/default/objects/Contact/fields/ConsecutiveAbsences__c.field-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fieldSets/SessionParticipantView.fieldSet-meta.xml
  force-app/main/default/objects/ProgramEngagement__c/fields/ConsecutiveAbsences__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: in QE review
