Repository SalesforceFoundation/PMM, pull requests merged in 2022-02, with the labels that each got.

#559 Enable recent sessions for experience cloud
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/recentSessions/recentSessions.js-meta.xml
Labels: ready for review, in dev review

#569 Attendance Component Row UI Enhancement
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/staticresources/pmm/attendancePrintOverride.css
Labels: in dev review, cla:signed

#570 Filter Service Participants that show up on Track Attendance by status, role and stage
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/ServiceDeliverySelector.cls
  force-app/main/default/classes/ServiceDeliveryService.cls
  force-app/main/default/classes/ServiceDeliveryService_TEST.cls
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendance/attendance.js-meta.xml
Labels: ready for review

#571 Add buckets for service sessions
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/RecentServiceSessionController.cls
  force-app/main/default/classes/RecentServiceSessionController_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/classes/ServiceSessionService.cls
  force-app/main/default/classes/ServiceSessionService_TEST.cls
  force-app/main/default/customMetadata/Bucket.Complete.md-meta.xml
  force-app/main/default/customMetadata/Bucket.Pending.md-meta.xml
  force-app/main/default/customMetadata/BucketedField.ServiceSessionStatuses.md-meta.xml
  force-app/main/default/customMetadata/BucketedValue.Complete.md-meta.xml
  force-app/main/default/customMetadata/BucketedValue.Pending.md-meta.xml
  force-app/main/default/lwc/attendance/__tests__/attendance.test.js
  force-app/main/default/lwc/attendance/__tests__/data/wiredGetSessionStatuses.json
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/recentSessions/recentSessions.html
  force-app/main/default/lwc/recentSessions/recentSessions.js
  force-app/main/default/lwc/sessionCard/sessionCard.js
Labels: ready for review

#576 Update attendance storytelling data
  cumulusci.yml
  datasets/mapping.yml
  datasets/sample.sql
  scripts/Update_Service_Sessions.apex
  scripts/Use_Alternate_Field_Sets.apex
  unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/AltAttendance.fieldSet-meta.xml
Labels: ready for RE review

#577 Feature/238 Allow Admins to determine Service Session status after submit
  force-app/main/default/classes/ServiceSessionService.cls
  force-app/main/default/classes/ServiceSessionStatusPicklist.cls
  force-app/main/default/classes/ServiceSessionStatusPicklist.cls-meta.xml
  force-app/main/default/classes/ServiceSessionStatusPicklist_TEST.cls
  force-app/main/default/classes/ServiceSessionStatusPicklist_TEST.cls-meta.xml
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendance/attendance.js-meta.xml
Labels: ready for review
