Repository SalesforceFoundation/PMM, pull requests merged in 2022-07, with the labels that each got.

#629 Screen readers announcing the day of the week selected
  force-app/main/default/lwc/picklist/picklist.html
  force-app/main/default/lwc/picklist/picklist.js
Labels: ready for review

#630 WIP: Added error banner for Service Delivery Defaults in BSDT
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.html
  force-app/main/default/lwc/serviceDeliveryDefaults/serviceDeliveryDefaults.js
Labels: ready for review

#634 Fix Monthly Schedule
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
Labels: in QE review

#635 Add text notifying the user they cannot modify or remove existing sessions
  force-app/main/default/labels/CustomLabels.labels-meta.xml
Labels: in dev review
