Repository SalesforceFoundation/PMM, pull requests merged in 2022-06, with the labels that each got.

#620 W-10999493: Option to delete all service deliveries on a service session
  force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveries.cmp
  force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveries.cmp-meta.xml
  force-app/main/default/aura/deleteServiceDeliveries/deleteServiceDeliveriesController.js
  force-app/main/default/classes/ServiceDeliveryController.cls
  force-app/main/default/classes/ServiceDeliveryController_TEST.cls
  force-app/main/default/classes/ServiceDeliveryDomain.cls
  force-app/main/default/classes/ServiceDeliveryDomain_TEST.cls
  force-app/main/default/classes/ServiceDeliverySelector.cls
  force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
  force-app/main/default/flexipages/Service_Schedule_Record_Page.flexipage-meta.xml
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/ServiceSession__c-Service Session Layout.layout-meta.xml
  force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.html
  force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.js
  force-app/main/default/lwc/serviceDeliveryDeleter/serviceDeliveryDeleter.js-meta.xml
  force-app/main/default/quickActions/ServiceSession__c.Delete_All_Service_Deliveries.quickAction-meta.xml
Labels: wip

#623 Do not set time if null on back and do not duplicate service sessions on back.
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
Labels: ready for review

#624 Display Capacity warning
  force-app/main/default/lwc/participantAdder/participantAdder.js
Labels: ready for review

#613 Script to delete Rosa's PSA.
  scripts/Delete_PMM_PSL_Assignments_Rosa.apex
Labels: ready for RE review

#625 Announce error message via screen reader
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.html
  force-app/main/default/lwc/serviceDeliveryRow/serviceDeliveryRow.js
Labels: ready for review
