Repository SalesforceFoundation/PMM, pull requests merged in 2022-05, with the labels that each got.

#607 Updated the locator for the Add Service participant modal save button
  robot/pmm/resources/locators_52.py
  robot/pmm/resources/pmm.py
  robot/pmm/tests/browser/ServiceSchedule/service_schedule_layout.robot
Labels: ready for RE review

#610 Add attendance summary field to Service Schedule
  force-app/main/default/classes/ServiceDeliveryRollupsService.cls
  force-app/main/default/classes/ServiceScheduleRollupsSchedulable.cls
  force-app/main/default/classes/ServiceScheduleRollupsSchedulable.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleRollupsSchedulable_TEST.cls
  force-app/main/default/classes/ServiceScheduleRollupsSchedulable_TEST.cls-meta.xml
  force-app/main/default/classes/SystemAccess.cls
  force-app/main/default/customMetadata/FeatureGate.ServiceDeliveriesToServiceSchedule.md-meta.xml
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/objects/ServiceDelivery__c/fields/ServiceSchedule__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/AttendanceRate__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/AttendanceSummary__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/NumAbsentServiceDeliveries__c.field-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/NumPresentServiceDeliveries__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
Labels: ready for review

#608 Track omitted attendance rows.
  force-app/main/default/classes/AttendanceController.cls
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/ServiceDeliverySelector.cls
  force-app/main/default/classes/ServiceDeliverySelector_TEST.cls
  force-app/main/default/classes/ServiceDeliveryService.cls
  force-app/main/default/classes/ServiceSessionDomain.cls
  force-app/main/default/classes/ServiceSessionDomain.cls-meta.xml
  force-app/main/default/classes/ServiceSessionDomain_TEST.cls
  force-app/main/default/classes/ServiceSessionDomain_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceSessionService.cls
  force-app/main/default/classes/ServiceSessionService_TEST.cls
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendanceRow/attendanceRow.css
  force-app/main/default/lwc/attendanceRow/attendanceRow.html
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
  force-app/main/default/objects/ServiceSession__c/fields/OmittedContactIds__c.field-meta.xml
Labels: in dev review

#612 Modal Close A11y Contrast
  force-app/main/default/lwc/modal/modal.html
Labels: ready for review

#615 Bucket for Program Cohort status
  force-app/main/default/classes/ProgramSelector.cls
  force-app/main/default/classes/ProgramSelector_TEST.cls
  force-app/main/default/customMetadata/Bucket.ProgramCohortStatusActive.md-meta.xml
  force-app/main/default/customMetadata/BucketedField.ProgramCohortStatuses.md-meta.xml
Labels: ready for review

#614 Allow fields of type Time to be used in Components surfacing field set fields
  force-app/main/default/classes/FieldSetService.cls
  force-app/main/default/classes/FieldSetService_TEST.cls
  force-app/main/default/lwc/attendanceRow/attendanceRow.js
  force-app/main/default/lwc/formattedField/formattedField.js
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
  force-app/main/default/lwc/util/util.js
Labels: ready for review

#606 W-10999318: Service Schedule "Add More Sessions" Wizard
  force-app/main/default/aura/addMoreSessions/addMoreSessions.cmp
  force-app/main/default/aura/addMoreSessions/addMoreSessions.cmp-meta.xml
  force-app/main/default/aura/addMoreSessions/addMoreSessionsController.js
  force-app/main/default/classes/ServiceScheduleCreatorController.cls
  force-app/main/default/classes/ServiceScheduleCreatorController_TEST.cls
  force-app/main/default/classes/ServiceScheduleDomain.cls
  force-app/main/default/classes/ServiceScheduleDomain_TEST.cls
  force-app/main/default/classes/ServiceScheduleModel.cls
  force-app/main/default/classes/ServiceScheduleSelector.cls
  force-app/main/default/classes/ServiceScheduleSelector.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleSelector_TEST.cls
  force-app/main/default/classes/ServiceScheduleSelector_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleService.cls
  force-app/main/default/classes/ServiceScheduleService_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/classes/ServiceSessionSelector_TEST.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.html
  force-app/main/default/lwc/newServiceSchedule/newServiceSchedule.js
  force-app/main/default/lwc/participantSelector/participantSelector.js
  force-app/main/default/lwc/picklist/picklist.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.html
  force-app/main/default/lwc/reviewSessions/reviewSessions.js
  force-app/main/default/lwc/reviewSessions/reviewSessions.js-meta.xml
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.html
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js
  force-app/main/default/lwc/serviceScheduleCreator/serviceScheduleCreator.js-meta.xml
  force-app/main/default/lwc/serviceScheduleCreatorWrapper/serviceScheduleCreatorWrapper.js-meta.xml
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.html
  force-app/main/default/lwc/serviceScheduleReview/serviceScheduleReview.js
  force-app/main/default/quickActions/ServiceSchedule__c.Add_More_Sessions.quickAction-meta.xml
Labels: ready for review

#617 Participant rollup on ServiceSchedule
  force-app/main/default/classes/ServiceParticipantRollupsService.cls
  force-app/main/default/classes/ServiceParticipantRollupsService.cls-meta.xml
  force-app/main/default/classes/ServiceParticipantRollupsService_TEST.cls
  force-app/main/default/classes/ServiceParticipantRollupsService_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceParticipantTriggerHandler.cls
  force-app/main/default/classes/ServiceParticipantTriggerHandler.cls-meta.xml
  force-app/main/default/classes/ServiceParticipantTriggerHandler_TEST.cls
  force-app/main/default/classes/ServiceParticipantTriggerHandler_TEST.cls-meta.xml
  force-app/main/default/classes/ServiceScheduleSelector.cls
  force-app/main/default/classes/ServiceScheduleSelector_TEST.cls
  force-app/main/default/classes/TestUtil.cls
  force-app/main/default/customMetadata/FeatureGate.ServiceParticipantsToServiceSchedule.md-meta.xml
  force-app/main/default/layouts/ServiceSchedule__c-Service Schedule Layout.layout-meta.xml
  force-app/main/default/objects/ServiceSchedule__c/fields/ParticipantsEnrolled__c.field-meta.xml
  force-app/main/default/permissionsets/PMDM_Deliver.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_Manage.permissionset-meta.xml
  force-app/main/default/permissionsets/PMDM_View.permissionset-meta.xml
  force-app/main/default/triggers/ServiceParticipantTrigger.trigger
  force-app/main/default/triggers/ServiceParticipantTrigger.trigger-meta.xml
Labels: ready for review
