Repository SalesforceFoundation/PMM, pull requests merged in 2022-03, with the labels that each got.

#579 Documentation Url Updates
  README.md
  metadeploy/labels_de.json
  metadeploy/labels_en-GB.json
  metadeploy/labels_en.json
  metadeploy/labels_es-MX.json
  metadeploy/labels_es.json
  metadeploy/labels_fr-CA.json
  metadeploy/labels_fr.json
  metadeploy/labels_ja.json
  metadeploy/labels_nl.json
Labels: in dev review

#578 Sort Program Cohorts alphabetically
  force-app/main/default/classes/ProgramSelector.cls
Labels: ready for review

#580 Update Unpackaged Dev Config for Alt Attendance Field Set
  unpackaged/config/alternate_field_sets/objects/___NAMESPACE___ServiceDelivery__c/fieldSets/AltAttendance.fieldSet-meta.xml
Labels: cla:signed

#582 Sort attendance by name
  force-app/main/default/classes/ServiceDeliverySelector.cls
  force-app/main/default/labels/CustomLabels.labels-meta.xml
  force-app/main/default/lwc/attendance/__tests__/attendance.test.js
  force-app/main/default/lwc/attendance/__tests__/data/wiredContactObjectInfo.json
  force-app/main/default/lwc/attendance/attendance.html
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/util/util.js
Labels: in QE review

#588 Update Service Session Bucket Names and Default Service Session Complete Status on the Attendance Component
  force-app/main/default/classes/AttendanceController_TEST.cls
  force-app/main/default/classes/ServiceSessionSelector.cls
  force-app/main/default/classes/ServiceSessionService.cls
  force-app/main/default/classes/ServiceSessionService_TEST.cls
  force-app/main/default/classes/ServiceSessionStatusPicklist.cls
  force-app/main/default/classes/ServiceSessionStatusPicklist_TEST.cls
  force-app/main/default/customMetadata/Bucket.ServiceSessionStatusComplete.md-meta.xml
  force-app/main/default/customMetadata/Bucket.ServiceSessionStatusPending.md-meta.xml
  force-app/main/default/customMetadata/BucketedValue.ServiceSessionStatusComplete.md-meta.xml
  force-app/main/default/customMetadata/BucketedValue.ServiceSessionStatusPending.md-meta.xml
  force-app/main/default/lwc/attendance/attendance.js
  force-app/main/default/lwc/attendance/attendance.js-meta.xml
  force-app/main/default/lwc/recentSessions/recentSessions.js
Labels: ready for review, in dev review

#591 [Robot] service session and schedule q3 test
  robot/pmm/resources/HomePageObject.py
  robot/pmm/resources/ServiceSchedulePageObject.py
  robot/pmm/resources/locators_52.py
  robot/pmm/tests/browser/HomePage/homepage_components.robot
  robot/pmm/tests/browser/ServiceSchedule/new_service_schedule.robot
Labels: 🤖 test
